export enum PermissionKey {
  TENANT_READ = "TENANT_READ",
  TENANT_UPDATE = "TENANT_UPDATE",
  PROJECT_CREATE = "PROJECT_CREATE",
  PROJECT_READ = "PROJECT_READ",
  PROJECT_UPDATE = "PROJECT_UPDATE",
  PROJECT_ARCHIVE = "PROJECT_ARCHIVE",
  COHORT_CREATE = "COHORT_CREATE",
  DATASET_CREATE = "DATASET_CREATE",
  ANALYSIS_RUN_CREATE = "ANALYSIS_RUN_CREATE",
  MANUSCRIPT_CREATE = "MANUSCRIPT_CREATE",
  AI_JOB_CREATE = "AI_JOB_CREATE",
  AUDIT_READ = "AUDIT_READ"
}
